name:                looper
version:             0.1.0.1
github:              "NorfairKing/looper"
license:             BSD3
author:              "Tom Sydney Kerckhove"
maintainer:          "syd@cs-syd.eu"
copyright:           "Copyright: (c) 2019-2020 Tom Sydney Kerckhove"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - aeson
  - envparse
  - optparse-applicative
  - text
  - time
  - unliftio
  - yamlparse-applicative >= 0.1


tests:
  looper-test:
    main:                Spec.hs
    source-dirs:         test
    build-tools:         sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - looper
    - optparse-applicative
    - sydtest
    - unliftio
