name:                looper
version:             0.0.0.0
github:              "NorfairKing/looper"
license:             BSD3
author:              "Tom Sydney Kerckhove"
maintainer:          "syd@cs-syd.eu"
copyright:           "Copyright: (c) 2019 Tom Sydney Kerckhove"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/NorfairKing/looper#readme>

dependencies:
- base >= 4.7 && < 5
- text
- optparse-applicative
- time
- unliftio
- aeson

library:
  source-dirs: src


tests:
  looper-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - looper
    - hspec
