resolver: lts-16.12
packages:
- looper
extra-deps:
- envparse-0.4.1
- github: NorfairKing/yamlparse-applicative
  commit: 7a329d06ffa45595963cf98f34910887115eb471
  subdirs:
    - yamlparse-applicative
- github: NorfairKing/safe-coloured-text
  commit: 2c8698978faf5556a6f928c5a55c797c3a262808
  subdirs:
    - safe-coloured-text
    - safe-coloured-text-terminfo
- github: NorfairKing/sydtest
  commit: 5e99c4fe56152d71982dcfba8bef4c79e19a9c8f
  subdirs:
    - sydtest
    - sydtest-discover
