resolver: lts-24.16
packages:
- looper

extra-deps:
- github: NorfairKing/safe-coloured-text
  commit: 046f10147a058c00c2706d98c341219e3cbc7669
  subdirs:
  - safe-coloured-text
  - safe-coloured-text-layout
  - safe-coloured-text-gen
- github: NorfairKing/autodocodec
  commit: d5f9869861d8678c7e6dfce339446fee490b8991
  subdirs:
    - autodocodec
    - autodocodec-nix
    - autodocodec-schema
    - autodocodec-yaml
- github: NorfairKing/opt-env-conf
  commit: 1a8d79f4748ae566c525de8951ee6907ac3739a8
  subdirs:
    - opt-env-conf
    - opt-env-conf-test

system-ghc: true
nix:
  enable: false
with-hpack: hpack
