resolver: lts-18.16
packages:
- looper
extra-deps:
- github: NorfairKing/autodocodec
  commit: 9880ec062f1166bdac50b8eb59c6dd010bc9af0c
  subdirs:
    - autodocodec
    - autodocodec-schema
    - autodocodec-yaml
- github: NorfairKing/safe-coloured-text
  commit: 7f157485e55528648a95edf3508a122b2e55779e
  subdirs:
    - safe-coloured-text
    - safe-coloured-text-terminfo
- github: NorfairKing/sydtest
  commit: e75c55b920936e344b779093b2a0318fb35d1770
  subdirs:
    - sydtest
    - sydtest-discover
