resolver: lts-16.12
packages:
- looper
extra-deps:
- envparse-0.4.1
- github: NorfairKing/autodocodec
  commit: c1687a96fcd98be2e4aece275342dbb39011be19
  subdirs:
    - autodocodec
    - autodocodec-schema
    - autodocodec-yaml
- github: NorfairKing/safe-coloured-text
  commit: 7f157485e55528648a95edf3508a122b2e55779e
  subdirs:
    - safe-coloured-text
    - safe-coloured-text-terminfo
- github: NorfairKing/sydtest
  commit: e75c55b920936e344b779093b2a0318fb35d1770
  subdirs:
    - sydtest
    - sydtest-discover
