resolver: lts-18.16
packages:
- looper
extra-deps:
- github: NorfairKing/autodocodec
  commit: 38bd4865ff2dd40d342141b7fde9319f835d98c6
  subdirs:
    - autodocodec
    - autodocodec-schema
    - autodocodec-yaml
- github: NorfairKing/safe-coloured-text
  commit: 71c5940a3b84eeb498304d8e584e7638f875d51b
  subdirs:
    - safe-coloured-text
    - safe-coloured-text-terminfo
- github: NorfairKing/sydtest
  commit: e55fad0f6b8058a9b44c6c0d66bdd3c3be556d71
  subdirs:
    - sydtest
    - sydtest-discover
