name: looper
version: 0.3.0.2
github: "NorfairKing/looper"
license: MIT
author: "Tom Sydney Kerckhove"
maintainer: "syd@cs-syd.eu"
copyright: "Copyright: (c) 2019-2022 Tom Sydney Kerckhove"
description: Configure and run recurring jobs indefinitely

dependencies:
- base >= 4.7 && < 5

extra-source-files:
- ChangeLog.md
- test_resources/**/*

library:
  source-dirs: src
  dependencies:
  - opt-env-conf
  - text
  - time
  - unliftio

tests:
  looper-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - looper
    - opt-env-conf
    - opt-env-conf-test
    - sydtest
    - unliftio
